name: "Type Check Apps"
description: "Type check all applications"
runs:
  using: "composite"
  steps:
    - name: Type check apps
      run: |
        pnpm --filter @wordsearchy/frontend type-check
        pnpm --filter @wordsearchy/multiplayer-game type-check
        pnpm --filter @wordsearchy/functions type-check
      shell: bash
