name: "Build Apps"
description: "Build all applications"
runs:
  using: "composite"
  steps:
    - name: Build apps
      run: |
        pnpm --filter @wordsearchy/frontend build
        pnpm --filter @wordsearchy/multiplayer-game build
        pnpm --filter @wordsearchy/functions build
      shell: bash
